name: CI
on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21.3
      - uses: actions/checkout@v4
      - name: Build the project
        run: make local_buil

  docker-push-api:
    name: Build and push api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push container
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/movies-api:latest

  build_and_push:
    needs:
      - docker-push-api
      - docker-push-notifications
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: copy files via ssh secrets
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "containers/docker-compose.yaml, configs/"
          target: "backend"
          rm: true
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker exec -i postgresql /bin/bash -c "pg_dump --username postgres movies_library" > ~/backup/dump.sql
            docker rm -f $(docker ps -aq)

            cd ~/backend/containers
            mv ../migrations .
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/movies-api
            docker compose up -d
